---
- name: Install Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - htop
- name: set language pack
  shell: locale-gen en_GB.UTF-8
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
